CREATE TABLE T_TABLE (CREATE_TIME VARCHAR(14) not null,MODIFY_TIME VARCHAR(14) not null,ENABLE CHAR(1) not null,NAME VARCHAR(10),OLD INTEGER not null,SEX BYTE(1) not null,COMMENT VARCHAR(10));
ALTER TABLE T_TABLE ADD PRIMARY KEY (NAME);
